CREATE TABLE province (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    ghn_province_id BIGINT NOT NULL UNIQUE,

    name VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);